from pathlib import Path

# Paths
RAW_DIR = Path('/Volumes/T9/monthly/')
PROCESSED_DIR = Path('/Users/clamalo/documents/harpnet/v3.1/tiles/')

# Tile domain coordinates
PRIMARY_MIN_LAT, PRIMARY_MAX_LAT = 34.0, 50.0
PRIMARY_MIN_LON, PRIMARY_MAX_LON = -125.0, -104.

SECONDARY_MIN_LAT, SECONDARY_MAX_LAT = 36.0, 48.0
SECONDARY_MIN_LON, SECONDARY_MAX_LON = -123.0, -106.0

# Tile settings
TILE_SIZE = 64
COARSE_RESOLUTION = 0.25
FINE_RESOLUTION = 0.0625
PADDING = 0.25

# TRAINING RUN SETTINGS
SECONDARY_TILES = True
SAVE_PRECISION = 'float16'
INCLUDE_ZEROS = True

BATCH_SIZE = 32

# TRAINING DATA SETTINGS
START_MONTH = (2020, 10)
END_MONTH = (2021, 2)
TRAIN_SPLIT = 0.8
# TRAIN_SPLIT = (1980, 2)
TRAINING_TILES = [0, 1]